services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dbnet

  pgadmin:
    image: dpage/pgadmin4:9.13.0
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: 3#w4vUP!ke0bm9Hx
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - dbnet

  valkey:
    image: valkey/valkey:9-alpine
    container_name: valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    networks:
      - dbnet

  infisical:
    image: infisical/infisical:v0.158.7
    container_name: infisical
    environment:
      NODE_ENV: production
      DB_CONNECTION_URI: postgresql://postgres:postgres@postgres:5432/infisical
      REDIS_URL: redis://valkey:6379
      ENCRYPTION_KEY: a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4
      AUTH_SECRET: a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1
      SITE_URL: http://localhost:8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - valkey
    networks:
      - dbnet

volumes:
  pgdata:
  pgadmin_data:
  valkey_data:

networks:
  dbnet:
